name: Show Runner RAM

on:
  push:
    branches:
      - main

jobs:
  show-ram:
    runs-on: ubuntu-latest
    steps:
      - name: Check available memory
        run: |
          echo "Total memory:"
          free -h
          echo ""
          echo "Memory details from /proc/meminfo:"
          head -n 5 /proc/meminfo
